OPTIONS (ERRORS=1008)
LOAD DATA 
INFILE 'D:\DB\DATA_TABLE\PROJ_SALE.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "PROJ_SALE"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"SALE_CODE" ,
"SALE_BOOK" ,
"SALE_MEM" CHAR (30),
"SALE_DATE" DATE "YYYY-MM-DD HH24:MI:SS" )
