OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'D:\DB\DATA_TABLE\PROJ_NOTICE.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "PROJ_NOTICE"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"NOTICE_CODE" ,
"NOTICE_TITLE" CHAR (100),
"NOTICE_CONTENT" CHAR (3000),
"NOTICE_DATE" DATE "YYYY-MM-DD HH24:MI:SS" )
