OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'D:\DB\DATA_TABLE\PROJ_MEMBER.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "PROJ_MEMBER"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"MEM_ID" CHAR (100),
"MEM_PW" CHAR (100),
"MEM_NAME" CHAR (100),
"MEM_ADDR" CHAR (150),
"MEM_TEL" CHAR (20),
"MEM_MANAGER" CHAR (1))
