OPTIONS (ERRORS=920)
LOAD DATA 
INFILE 'D:\db\DATA_TABLE\PROJ_REV.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "PROJ_REV"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"REV_CODE" ,
"REV_SCORE" ,
"REV_CONTENT" CHAR (500))
