--------------------------------------------------------
--  DDL for Table PROJ_MEMBER
--------------------------------------------------------

  CREATE TABLE "PROJ_MEMBER" 
   (	"MEM_ID" VARCHAR2(100 BYTE), 
	"MEM_PW" VARCHAR2(100 BYTE), 
	"MEM_NAME" VARCHAR2(100 BYTE), 
	"MEM_ADDR" VARCHAR2(150 BYTE), 
	"MEM_TEL" VARCHAR2(20 BYTE), 
	"MEM_MANAGER" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
