--------------------------------------------------------
--  DDL for Table PROJ_BOOKS
--------------------------------------------------------

  CREATE TABLE "PROJ_BOOKS" 
   (	"BOOK_CODE" NUMBER(13,0), 
	"BOOK_TITLE" VARCHAR2(200 BYTE), 
	"BOOK_PRICE" NUMBER(6,0), 
	"BOOK_AUTHOR" VARCHAR2(100 BYTE), 
	"BOOK_PUB" VARCHAR2(100 BYTE), 
	"BOOK_DATE" DATE, 
	"BOOK_GENRE" VARCHAR2(20 BYTE), 
	"BOOK_IMGNAME" VARCHAR2(50 BYTE), 
	"BOOK_IMAGE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("BOOK_IMAGE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
