--------------------------------------------------------
--  Constraints for Table PROJ_SALE
--------------------------------------------------------

  ALTER TABLE "PROJ_SALE" ADD PRIMARY KEY ("SALE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PROJ_SALE" MODIFY ("SALE_BOOK" NOT NULL ENABLE);
  ALTER TABLE "PROJ_SALE" MODIFY ("SALE_MEM" NOT NULL ENABLE);
  ALTER TABLE "PROJ_SALE" MODIFY ("SALE_DATE" NOT NULL ENABLE);
