--------------------------------------------------------
--  Constraints for Table PROJ_BOOKS
--------------------------------------------------------

  ALTER TABLE "PROJ_BOOKS" ADD PRIMARY KEY ("BOOK_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PROJ_BOOKS" MODIFY ("BOOK_TITLE" NOT NULL ENABLE);
  ALTER TABLE "PROJ_BOOKS" MODIFY ("BOOK_PRICE" NOT NULL ENABLE);
  ALTER TABLE "PROJ_BOOKS" MODIFY ("BOOK_AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "PROJ_BOOKS" MODIFY ("BOOK_PUB" NOT NULL ENABLE);
  ALTER TABLE "PROJ_BOOKS" MODIFY ("BOOK_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROJ_BOOKS" MODIFY ("BOOK_GENRE" NOT NULL ENABLE);
