--------------------------------------------------------
--  Constraints for Table PROJ_MEMBER
--------------------------------------------------------

  ALTER TABLE "PROJ_MEMBER" ADD PRIMARY KEY ("MEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PROJ_MEMBER" MODIFY ("MEM_MANAGER" NOT NULL ENABLE);
  ALTER TABLE "PROJ_MEMBER" MODIFY ("MEM_PW" NOT NULL ENABLE);
  ALTER TABLE "PROJ_MEMBER" MODIFY ("MEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJ_MEMBER" MODIFY ("MEM_ADDR" NOT NULL ENABLE);
  ALTER TABLE "PROJ_MEMBER" MODIFY ("MEM_TEL" NOT NULL ENABLE);
